plugins {
    id 'com.android.application'
    id 'kotlin-android'
    id 'kotlin-kapt'
}

android {
    namespace "com.mozhimen.basick.test"
    compileSdk 35

    defaultConfig {
        applicationId "com.mozhimen.basick.test"
        minSdk 24
        targetSdk 25
        versionCode 1
        versionName "1.0.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
    buildFeatures{
        dataBinding true
    }
    lintOptions {
        checkReleaseBuilds false
        abortOnError false
    }
}

configurations.configureEach {
    resolutionStrategy.dependencySubstitution {
        substitute module(
                'com.github.mozhimen.ASwiftKit:basick'
        ) using project(':basick')

        substitute module(
                'com.github.mozhimen.ASwiftKit:xmlk'
        ) using project(':xmlk')

        substitute module(
                'com.github.mozhimen.ASwiftKit:uik'
        ) using project(':uik')

        substitute module(
                'com.github.mozhimen.ASwiftKit:uik-databinding'
        ) using project(':uik-databinding')
    }
}

dependencies {
    implementation project(':uik-databinding')
    implementation project(':xmlk')
    implementation 'com.github.mozhimen.AStackKit:stackk:0.0.1'
    implementation 'com.github.mozhimen.AXmlKit:dialogk:0.0.7'
    implementation 'com.github.mozhimen.AXmlKit:dialogk-databinding:0.0.7'
    implementation 'com.github.mozhimen.AAnimKit:animk:0.0.1'

    //test
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
}